### ISSUE TITLE
ETQ Dev : Je réfléchis au modèle de compensation multicritère

### ISSUE THREAD

**Issue by JapanKyutsu** [JapanKyutsu/apartments#7]
Énoncé : 

> Un utilisateur indique son utilité (en argent) concernant les différents aspects d’un appartement. Pour chaque critère (ex nb pièces) il indique combien il est prêt à donner pour passer d’une valeur à une autre (ex 30 € pour gagner un mètre carré).

Je dois réfléchir aux critères (qui sont les mêmes que le modèle de donnée Apartment), comment les pondérer, les hiérarchiser, et quelle en est la sortie (Liste d'appartement triée?). Je dois également étudier les utilités associées par l'utilisateur (Ex. 30€ pour gagner 1 mètre carré). 

Ce modèle doit être le plus indépendant et générique possible (très peu de dépendances vis à vis de d'autres classes), si possible standalone, comprendre qu'on peut facilement exporter ce modèle et le réutiliser autre part. 

Je propose une première implémentation.

**Comment by cqro33** [comment]
Model implemented without the "exchange utilities" functionality.

**Comment by cqro33** [comment]
Model thought with "exchange utility", math demo in the attached file. 
[Utilité du consommateur v2.pdf](https://github.com/JapanKyutsu/apartments/files/755324/Utilite.du.consommateur.v2.pdf)
